apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gowpos-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gowpos-secret-store
    kind: ClusterSecretStore
  target:
    name: gowpos-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: gowpos/db
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: gowpos/cache
        property: REDIS_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: gowpos/backend
        property: JWT_SECRET
