apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gowpos
resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - configmap.yaml
  - external-secret.yaml
  - monitoring.yaml
