apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gowpos-backend
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: gowpos-backend
  namespaceSelector:
    matchNames:
      - gowpos
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gowpos-frontend
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: gowpos-frontend
  namespaceSelector:
    matchNames:
      - gowpos
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
