apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gowpos-staging
resources:
  - ../base
namePrefix: staging-
commonLabels:
  env: staging
patches:
  - target:
      kind: Deployment
      name: gowpos-backend
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gowpos-backend
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: backend
                env:
                  - name: LOG_LEVEL
                    value: debug
  - target:
      kind: ConfigMap
      name: gowpos-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gowpos-config
      data:
        apiUrl: https://staging-api.gowpos.com
        frontendUrl: https://staging-app.gowpos.com
